# Generated by Django 2.0.7 on 2018-10-03 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_reply_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments', to='thread.Post_reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
